# Generated by Django 4.1.5 on 2023-01-30 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_num', models.PositiveIntegerField(default=1)),
                ('driver', models.CharField(default='', max_length=20, null=True)),
                ('ifShare', models.BooleanField(default=False)),
                ('sharer', models.CharField(default='', max_length=20, null=True)),
                ('sharer_num', models.PositiveIntegerField(default=0)),
                ('pickup', models.CharField(max_length=100)),
                ('whereto', models.CharField(max_length=100)),
                ('schedule', models.DateTimeField(help_text='Format: 2023-02-01 06:00')),
                ('extraInfo', models.CharField(max_length=200)),
                ('car_type', models.CharField(choices=[('SUV', 'SUV'), ('COMPACT', 'COMPACT'), ('COMFORT', 'COMFORT'), ('GREEN', 'GREEN'), ('PREMIER', 'PREMIER')], default='SUV', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('COMFIRM', 'COMFIRM'), ('COMPLETE', 'COMPLETE')], default='OPEN', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_num', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=18, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('drive', models.BooleanField(default=False)),
                ('license_num', models.CharField(max_length=20, null=True)),
                ('license_plate', models.CharField(max_length=20, null=True)),
                ('car_type', models.CharField(choices=[('SUV', 'SUV'), ('COMPACT', 'COMPACT'), ('COMFORT', 'COMFORT'), ('GREEN', 'GREEN'), ('PREMIER', 'PREMIER')], default='SUV', max_length=20, null=True)),
                ('car_brand', models.CharField(max_length=20, null=True)),
                ('capacity', models.PositiveIntegerField(default=0, null=True)),
                ('user_name', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
