# Generated by Django 4.1.5 on 2023-01-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='car_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('COMPACT', 'COMPACT'), ('COMFORT', 'COMFORT'), ('GREEN', 'GREEN'), ('PREMIER', 'PREMIER')], default='SUV', max_length=20),
        ),
    ]
