# Generated by Django 4.1.5 on 2023-01-29 19:03

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tel',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
