# Generated by Django 4.1.5 on 2023-01-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_account_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
