# Generated by Django 4.1.5 on 2023-01-29 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
