# Generated by Django 4.1.5 on 2023-01-29 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_remove_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field = models.CharField(max_length=200, null=True)
            # field=models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
