# Generated by Django 4.1.5 on 2023-01-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_account_name_account_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
