# Generated by Django 4.1.5 on 2023-01-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='account',
            name='car_brand',
        ),
        migrations.RemoveField(
            model_name='account',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='license_num',
        ),
        migrations.RemoveField(
            model_name='account',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='extraInfo',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ifShare',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='sharer',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='sharer_num',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='whereto',
        ),
    ]
