# Generated by Django 4.1.5 on 2023-01-29 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_alter_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        # migrations.AlterField(
        #     model_name='account',
        #     name='username',
        #     field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
    ]
