# Generated by Django 4.1.5 on 2023-01-30 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_remove_account_capacity_remove_account_car_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_name',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
