# Generated by Django 4.1.5 on 2023-01-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='user_name',
            new_name='username',
        ),
    ]
