# Generated by Django 4.1.5 on 2023-01-29 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
