# Generated by Django 4.1.5 on 2023-01-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_userdetail_capacity_userdetail_car_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='car_type',
            field=models.CharField(blank=True, choices=[('SUV', 'SUV'), ('COMPACT', 'COMPACT'), ('COMFORT', 'COMFORT'), ('GREEN', 'GREEN'), ('PREMIER', 'PREMIER')], default='', max_length=20, null=True),
        ),
    ]
