# Generated by Django 4.1.5 on 2023-01-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_account_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='capacity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='car_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('COMPACT', 'COMPACT'), ('COMFORT', 'COMFORT'), ('GREEN', 'GREEN'), ('PREMIER', 'PREMIER')], default='SUV', max_length=20, null=True),
        ),
    ]
