# Generated by Django 4.1.5 on 2023-01-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_account_capacity_alter_account_car_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_address', models.CharField(default='', max_length=200)),
                ('required_arrival_time', models.DateTimeField()),
                ('total_passenger_number', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(max_length=200, null=True)),
                ('special_request', models.TextField(max_length=2000)),
            ],
        ),
    ]
