# Generated by Django 4.1.5 on 2023-01-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_ride_car_type_ride_driver_ride_extrainfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='schedule',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
