# Generated by Django 4.1.5 on 2023-01-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_ride_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
