# Generated by Django 4.1.5 on 2023-02-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_ride_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
