# Generated by Django 4.1.5 on 2023-02-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_ride_multisharer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='multiSharer',
            field=models.ManyToManyField(blank=True, related_name='multiSharer', to='account.userdetail'),
        ),
    ]
